source 'https://rubygems.org'
ruby '2.5.0'
# ruby '2.3.3', :engine => 'jruby', :engine_version => '9.1.15.0'

gem 'bcrypt',        '~> 3.1', '>= 3.1.11'
# gem 'byebug'
gem 'database_cleaner'
gem 'foreman'
gem 'json'
gem 'minitest',      '~> 5.8', '>= 5.8.4'
gem 'mongoid',       '~> 6.3'
gem 'newrelic_rpm'
gem 'puma'
gem 'rack-minitest'
gem 'rake'
gem 'rest-client'
gem 'sinatra',       '2.0.1'
gem 'sinatra-contrib'
gem 'sinatra-flash', '~> 0.3.0'
gem 'redis'
gem 'sidekiq'
gem 'rack-timeout', require:'rack/timeout/base'
gem 'sinatra-cache', '0.3.2'
