source 'https://rubygems.org'
ruby '2.5.0'

gem 'bcrypt',        '~> 3.1', '>= 3.1.11'
gem 'byebug'
gem 'database_cleaner'
gem 'minitest',      '~> 5.8', '>= 5.8.4'
gem 'mongoid',       '~> 6.3'
gem 'rack-minitest'
gem 'rake'
gem 'rest-client'
gem 'sinatra',       '2.0.1'
gem 'sinatra-contrib'
gem 'sinatra-flash', '~> 0.3.0'
gem 'redis'
