test:
  clients:
    default:
      database: nanotwitter-test
      hosts:
        - localhost: 27017


development:
  clients:
    default:
      database: nanotwitter-dev
      hosts:
        - localhost: 27017

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>