<% if ENV['MONGOLAB_URI'] %>
production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
<% else %>
test:
  clients:
    unit-test:
      database: nanotwitter-test
      hosts:
        - localhost: 27017
    load-test:
      database: nanotwitter_loadtest
      hosts:
        - localhost: 27017

development:
  clients:
    default:
      database: nanotwitter-dev
      hosts:
        - localhost: 27017
<% end %>