test:
  clients:
    unit-test:
      database: nanotwitter-test
      hosts:
        - localhost: 27017
    load-test:
      database: nanotwitter_loadtest
      hosts:
        - localhost: 27017

development:
  sessions:
    default:
      database: nanotwitter-dev
      hosts:
        - localhost: 27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>